parameters:
    oro_soap.request.class:           Oro\Bundle\SoapBundle\Entity\RequestFix
    oro_soap.loader.class:            Oro\Bundle\SoapBundle\ServiceDefinition\Loader\OroSoapLoader

services:
    oro_soap.request:
        class:                        %oro_soap.request.class%
        scope:                        request
        arguments:
            - "@oro_flexibleentity.registry"

    oro_soap.loader:
        class:                        %oro_soap.loader.class%
        arguments:                    ["@file_locator", "@besimple.soap.definition.loader.annot_class"]
        public:                       false
        tags:
            - { name: besimple.soap.definition.loader }
